# Generated by Django 5.2.10 on 2026-01-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=200)),
                ("university", models.CharField(max_length=200)),
                ("school", models.CharField(max_length=200)),
                ("previous_work", models.CharField(max_length=200)),
                ("skills", models.CharField(max_length=200)),
            ],
        ),
    ]
